# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'jekyll', '>= 3.9.0'
gem 'github-pages', '>= 224', group: :jekyll_plugins
gem 'wdm', '~> 0.1.0' if Gem.win_platform?
